import countries from 'i18n-iso-countries';
import enLocale from 'i18n-iso-countries/langs/en.json';
import countryToCurrency from 'country-to-currency';
import getSymbolFromCurrency from 'currency-symbol-map';

countries.registerLocale(enLocale);

export interface CurrencyInfo {
  symbol: string;
  code: string;
  minRent: number;
  maxRent: number;
}

// ── Currency definitions ──────────────────────────────────────────────────
const CURRENCIES: Record<string, CurrencyInfo> = {
  USD: { symbol: "$", code: "USD", minRent: 500, maxRent: 8_000 },
  GBP: { symbol: "£", code: "GBP", minRent: 400, maxRent: 6_000 },
  EUR: { symbol: "€", code: "EUR", minRent: 400, maxRent: 6_000 },
  AUD: { symbol: "A$", code: "AUD", minRent: 600, maxRent: 8_000 },
  CAD: { symbol: "C$", code: "CAD", minRent: 600, maxRent: 7_000 },
  CHF: { symbol: "Fr", code: "CHF", minRent: 800, maxRent: 9_000 },
  SGD: { symbol: "S$", code: "SGD", minRent: 800, maxRent: 8_000 },
  HKD: { symbol: "HK$", code: "HKD", minRent: 5_000, maxRent: 80_000 },
  JPY: { symbol: "¥", code: "JPY", minRent: 50_000, maxRent: 350_000 },
  CNY: { symbol: "¥", code: "CNY", minRent: 1_500, maxRent: 25_000 },
  KRW: { symbol: "₩", code: "KRW", minRent: 400_000, maxRent: 4_000_000 },
  TWD: { symbol: "NT$", code: "TWD", minRent: 5_000, maxRent: 60_000 },
  INR: { symbol: "₹", code: "INR", minRent: 5_000, maxRent: 200_000 },
  PKR: { symbol: "₨", code: "PKR", minRent: 15_000, maxRent: 150_000 },
  BDT: { symbol: "৳", code: "BDT", minRent: 5_000, maxRent: 80_000 },
  LKR: { symbol: "Rs", code: "LKR", minRent: 8_000, maxRent: 100_000 },
  NPR: { symbol: "Rs", code: "NPR", minRent: 5_000, maxRent: 60_000 },
  THB: { symbol: "฿", code: "THB", minRent: 5_000, maxRent: 60_000 },
  VND: { symbol: "₫", code: "VND", minRent: 2_000_000, maxRent: 30_000_000 },
  IDR: { symbol: "Rp", code: "IDR", minRent: 1_500_000, maxRent: 25_000_000 },
  MYR: { symbol: "RM", code: "MYR", minRent: 600, maxRent: 6_000 },
  PHP: { symbol: "₱", code: "PHP", minRent: 5_000, maxRent: 80_000 },
  MMK: { symbol: "K", code: "MMK", minRent: 100_000, maxRent: 1_000_000 },
  KHR: { symbol: "៛", code: "KHR", minRent: 200_000, maxRent: 2_000_000 },
  BND: { symbol: "B$", code: "BND", minRent: 600, maxRent: 4_000 },
  MNT: { symbol: "₮", code: "MNT", minRent: 200_000, maxRent: 2_000_000 },
  KZT: { symbol: "₸", code: "KZT", minRent: 80_000, maxRent: 800_000 },
  UZS: { symbol: "so'm", code: "UZS", minRent: 500_000, maxRent: 5_000_000 },
  TRY: { symbol: "₺", code: "TRY", minRent: 2_000, maxRent: 40_000 },
  RUB: { symbol: "₽", code: "RUB", minRent: 15_000, maxRent: 200_000 },
  UAH: { symbol: "₴", code: "UAH", minRent: 5_000, maxRent: 80_000 },
  PLN: { symbol: "zł", code: "PLN", minRent: 800, maxRent: 6_000 },
  CZK: { symbol: "Kč", code: "CZK", minRent: 10_000, maxRent: 50_000 },
  HUF: { symbol: "Ft", code: "HUF", minRent: 80_000, maxRent: 600_000 },
  RON: { symbol: "lei", code: "RON", minRent: 800, maxRent: 5_000 },
  BGN: { symbol: "лв", code: "BGN", minRent: 300, maxRent: 2_500 },
  HRK: { symbol: "kn", code: "HRK", minRent: 2_000, maxRent: 15_000 },
  RSD: { symbol: "din", code: "RSD", minRent: 25_000, maxRent: 150_000 },
  DKK: { symbol: "kr", code: "DKK", minRent: 4_000, maxRent: 20_000 },
  SEK: { symbol: "kr", code: "SEK", minRent: 5_000, maxRent: 20_000 },
  NOK: { symbol: "kr", code: "NOK", minRent: 6_000, maxRent: 25_000 },
  ISK: { symbol: "kr", code: "ISK", minRent: 80_000, maxRent: 400_000 },
  ILS: { symbol: "₪", code: "ILS", minRent: 2_000, maxRent: 15_000 },
  SAR: { symbol: "SR", code: "SAR", minRent: 1_000, maxRent: 15_000 },
  AED: { symbol: "AED", code: "AED", minRent: 2_000, maxRent: 30_000 },
  QAR: { symbol: "QR", code: "QAR", minRent: 2_000, maxRent: 20_000 },
  KWD: { symbol: "KD", code: "KWD", minRent: 150, maxRent: 2_000 },
  BHD: { symbol: "BD", code: "BHD", minRent: 150, maxRent: 2_000 },
  OMR: { symbol: "OMR", code: "OMR", minRent: 150, maxRent: 2_000 },
  JOD: { symbol: "JD", code: "JOD", minRent: 200, maxRent: 2_000 },
  EGP: { symbol: "E£", code: "EGP", minRent: 1_500, maxRent: 25_000 },
  MAD: { symbol: "MAD", code: "MAD", minRent: 1_500, maxRent: 15_000 },
  TND: { symbol: "DT", code: "TND", minRent: 300, maxRent: 3_000 },
  DZD: { symbol: "DA", code: "DZD", minRent: 15_000, maxRent: 100_000 },
  LYD: { symbol: "LD", code: "LYD", minRent: 500, maxRent: 5_000 },
  NGN: { symbol: "₦", code: "NGN", minRent: 50_000, maxRent: 800_000 },
  GHS: { symbol: "GH₵", code: "GHS", minRent: 500, maxRent: 10_000 },
  KES: { symbol: "KSh", code: "KES", minRent: 10_000, maxRent: 200_000 },
  UGX: { symbol: "UGX", code: "UGX", minRent: 500_000, maxRent: 8_000_000 },
  TZS: { symbol: "TSh", code: "TZS", minRent: 150_000, maxRent: 2_000_000 },
  ETB: { symbol: "Br", code: "ETB", minRent: 2_000, maxRent: 30_000 },
  RWF: { symbol: "FRw", code: "RWF", minRent: 50_000, maxRent: 600_000 },
  ZAR: { symbol: "R", code: "ZAR", minRent: 3_000, maxRent: 50_000 },
  ZMW: { symbol: "K", code: "ZMW", minRent: 1_000, maxRent: 15_000 },
  MWK: { symbol: "MK", code: "MWK", minRent: 30_000, maxRent: 300_000 },
  AOA: { symbol: "Kz", code: "AOA", minRent: 30_000, maxRent: 500_000 },
  MZN: { symbol: "MT", code: "MZN", minRent: 2_000, maxRent: 30_000 },
  NAD: { symbol: "N$", code: "NAD", minRent: 3_000, maxRent: 20_000 },
  BWP: { symbol: "P", code: "BWP", minRent: 1_000, maxRent: 15_000 },
  XAF: { symbol: "Fr", code: "XAF", minRent: 30_000, maxRent: 300_000 },
  XOF: { symbol: "Fr", code: "XOF", minRent: 30_000, maxRent: 300_000 },
  CDF: { symbol: "Fr", code: "CDF", minRent: 50_000, maxRent: 500_000 },
  MXN: { symbol: "MX$", code: "MXN", minRent: 3_000, maxRent: 50_000 },
  BRL: { symbol: "R$", code: "BRL", minRent: 800, maxRent: 20_000 },
  ARS: { symbol: "AR$", code: "ARS", minRent: 50_000, maxRent: 500_000 },
  COP: { symbol: "COP$", code: "COP", minRent: 800_000, maxRent: 8_000_000 },
  CLP: { symbol: "CLP$", code: "CLP", minRent: 200_000, maxRent: 1_500_000 },
  PEN: { symbol: "S/", code: "PEN", minRent: 500, maxRent: 5_000 },
  BOB: { symbol: "Bs.", code: "BOB", minRent: 500, maxRent: 8_000 },
  PYG: { symbol: "₲", code: "PYG", minRent: 500_000, maxRent: 5_000_000 },
  UYU: { symbol: "$U", code: "UYU", minRent: 8_000, maxRent: 80_000 },
  GTQ: { symbol: "Q", code: "GTQ", minRent: 1_000, maxRent: 10_000 },
  HNL: { symbol: "L", code: "HNL", minRent: 3_000, maxRent: 30_000 },
  NIO: { symbol: "C$", code: "NIO", minRent: 3_000, maxRent: 20_000 },
  CRC: { symbol: "₡", code: "CRC", minRent: 150_000, maxRent: 1_500_000 },
  DOP: { symbol: "RD$", code: "DOP", minRent: 8_000, maxRent: 80_000 },
  JMD: { symbol: "J$", code: "JMD", minRent: 20_000, maxRent: 200_000 },
  TTD: { symbol: "TT$", code: "TTD", minRent: 1_500, maxRent: 15_000 },
  NZD: { symbol: "NZ$", code: "NZD", minRent: 600, maxRent: 5_000 },
  PGK: { symbol: "K", code: "PGK", minRent: 500, maxRent: 8_000 },
  FJD: { symbol: "FJ$", code: "FJD", minRent: 300, maxRent: 3_000 },
  MOP: { symbol: "P", code: "MOP", minRent: 3_000, maxRent: 20_000 },
  GEL: { symbol: "₾", code: "GEL", minRent: 600, maxRent: 6_000 },
  AMD: { symbol: "֏", code: "AMD", minRent: 50_000, maxRent: 500_000 },
  AZN: { symbol: "₼", code: "AZN", minRent: 200, maxRent: 2_000 },
  MDL: { symbol: "MDL", code: "MDL", minRent: 2_000, maxRent: 20_000 },
  ALL: { symbol: "L", code: "ALL", minRent: 15_000, maxRent: 120_000 },
  MKD: { symbol: "ден", code: "MKD", minRent: 5_000, maxRent: 40_000 },
  BAM: { symbol: "KM", code: "BAM", minRent: 300, maxRent: 2_000 },
  AFN: { symbol: "؋", code: "AFN", minRent: 3_000, maxRent: 30_000 },
  IRR: { symbol: "﷼", code: "IRR", minRent: 3_000_000, maxRent: 50_000_000 },
  IQD: { symbol: "IQD", code: "IQD", minRent: 200_000, maxRent: 2_000_000 },
  SYP: { symbol: "£S", code: "SYP", minRent: 50_000, maxRent: 500_000 },
  LBP: { symbol: "LL", code: "LBP", minRent: 500_000, maxRent: 10_000_000 },
  YER: { symbol: "﷼", code: "YER", minRent: 30_000, maxRent: 300_000 },
  SDG: { symbol: "SDG", code: "SDG", minRent: 5_000, maxRent: 80_000 },
  SOS: { symbol: "Sh", code: "SOS", minRent: 50_000, maxRent: 500_000 },
  BYN: { symbol: "Br", code: "BYN", minRent: 300, maxRent: 3_000 },
  MGA: { symbol: "Ar", code: "MGA", minRent: 100_000, maxRent: 1_000_000 },
  MUR: { symbol: "Rs", code: "MUR", minRent: 5_000, maxRent: 50_000 },
  SCR: { symbol: "Rs", code: "SCR", minRent: 2_000, maxRent: 20_000 },
  KGS: { symbol: "som", code: "KGS", minRent: 5_000, maxRent: 50_000 },
  TJS: { symbol: "SM", code: "TJS", minRent: 500, maxRent: 5_000 },
  TMT: { symbol: "T", code: "TMT", minRent: 300, maxRent: 3_000 },
};

// ── Country name → currency code ─────────────────────────────────────────
const COUNTRY: Record<string, string> = {
  // Americas
  "united states": "USD",
  usa: "USD",
  us: "USD",
  america: "USD",
  canada: "CAD",
  mexico: "MXN",
  brazil: "BRL",
  argentina: "ARS",
  colombia: "COP",
  chile: "CLP",
  peru: "PEN",
  venezuela: "USD",
  ecuador: "USD",
  bolivia: "BOB",
  paraguay: "PYG",
  uruguay: "UYU",
  guyana: "USD",
  suriname: "USD",
  "french guiana": "EUR",
  guatemala: "GTQ",
  honduras: "HNL",
  "el salvador": "USD",
  nicaragua: "NIO",
  "costa rica": "CRC",
  panama: "USD",
  cuba: "USD",
  haiti: "USD",
  "dominican republic": "DOP",
  "puerto rico": "USD",
  jamaica: "JMD",
  "trinidad and tobago": "TTD",
  trinidad: "TTD",
  barbados: "USD",
  bahamas: "USD",
  belize: "USD",

  // Europe
  "united kingdom": "GBP",
  uk: "GBP",
  "great britain": "GBP",
  britain: "GBP",
  england: "GBP",
  scotland: "GBP",
  wales: "GBP",
  "northern ireland": "GBP",
  germany: "EUR",
  france: "EUR",
  italy: "EUR",
  spain: "EUR",
  portugal: "EUR",
  netherlands: "EUR",
  holland: "EUR",
  belgium: "EUR",
  austria: "EUR",
  ireland: "EUR",
  finland: "EUR",
  greece: "EUR",
  luxembourg: "EUR",
  slovakia: "EUR",
  slovenia: "EUR",
  estonia: "EUR",
  latvia: "EUR",
  lithuania: "EUR",
  malta: "EUR",
  cyprus: "EUR",
  switzerland: "CHF",
  swiss: "CHF",
  sweden: "SEK",
  norway: "NOK",
  denmark: "DKK",
  iceland: "ISK",
  poland: "PLN",
  "czech republic": "CZK",
  czechia: "CZK",
  hungary: "HUF",
  romania: "RON",
  bulgaria: "BGN",
  croatia: "HRK",
  serbia: "RSD",
  bosnia: "BAM",
  "bosnia and herzegovina": "BAM",
  "north macedonia": "MKD",
  macedonia: "MKD",
  albania: "ALL",
  ukraine: "UAH",
  russia: "RUB",
  "russian federation": "RUB",
  belarus: "BYN",
  moldova: "MDL",
  georgia: "GEL",
  armenia: "AMD",
  azerbaijan: "AZN",
  turkey: "TRY",
  turkiye: "TRY",
  kosovo: "EUR",
  montenegro: "EUR",
  liechtenstein: "CHF",
  andorra: "EUR",
  monaco: "EUR",
  "san marino": "EUR",
  vatican: "EUR",

  // Asia-Pacific
  china: "CNY",
  "peoples republic of china": "CNY",
  japan: "JPY",
  "south korea": "KRW",
  korea: "KRW",
  taiwan: "TWD",
  "hong kong": "HKD",
  macau: "MOP",
  macao: "MOP",
  india: "INR",
  pakistan: "PKR",
  bangladesh: "BDT",
  "sri lanka": "LKR",
  ceylon: "LKR",
  nepal: "NPR",
  myanmar: "MMK",
  burma: "MMK",
  thailand: "THB",
  vietnam: "VND",
  "viet nam": "VND",
  cambodia: "KHR",
  laos: "LAK",
  malaysia: "MYR",
  singapore: "SGD",
  indonesia: "IDR",
  philippines: "PHP",
  brunei: "BND",
  "timor leste": "USD",
  "east timor": "USD",
  mongolia: "MNT",
  kazakhstan: "KZT",
  uzbekistan: "UZS",
  kyrgyzstan: "KGS",
  tajikistan: "TJS",
  turkmenistan: "TMT",
  afghanistan: "AFN",
  australia: "AUD",
  aus: "AUD",
  "new zealand": "NZD",
  nz: "NZD",
  "papua new guinea": "PGK",
  png: "PGK",
  fiji: "FJD",
  "solomon islands": "USD",
  vanuatu: "USD",
  samoa: "USD",
  tonga: "USD",
  kiribati: "USD",
  maldives: "USD",
  bhutan: "USD",

  // Middle East
  "saudi arabia": "SAR",
  ksa: "SAR",
  uae: "AED",
  "united arab emirates": "AED",
  emirates: "AED",
  qatar: "QAR",
  kuwait: "KWD",
  bahrain: "BHD",
  oman: "OMR",
  jordan: "JOD",
  israel: "ILS",
  palestine: "ILS",
  lebanon: "LBP",
  syria: "SYP",
  iraq: "IQD",
  iran: "IRR",
  persia: "IRR",
  yemen: "YER",

  // Africa — North
  egypt: "EGP",
  morocco: "MAD",
  algeria: "DZD",
  tunisia: "TND",
  libya: "LYD",
  sudan: "SDG",
  "south sudan": "USD",

  // Africa — West
  nigeria: "NGN",
  ghana: "GHS",
  senegal: "XOF",
  "ivory coast": "XOF",
  "cote divoire": "XOF",
  mali: "XOF",
  "burkina faso": "XOF",
  niger: "XOF",
  benin: "XOF",
  togo: "XOF",
  guinea: "USD",
  "guinea bissau": "XOF",
  "sierra leone": "USD",
  liberia: "USD",
  gambia: "USD",
  "cape verde": "USD",

  // Africa — Central
  cameroon: "XAF",
  "central african republic": "XAF",
  car: "XAF",
  chad: "XAF",
  gabon: "XAF",
  "republic of the congo": "XAF",
  "congo brazzaville": "XAF",
  "equatorial guinea": "XAF",
  "democratic republic of congo": "CDF",
  drc: "CDF",
  "congo kinshasa": "CDF",

  // Africa — East
  kenya: "KES",
  tanzania: "TZS",
  uganda: "UGX",
  ethiopia: "ETB",
  rwanda: "RWF",
  burundi: "USD",
  somalia: "SOS",
  djibouti: "USD",
  eritrea: "USD",

  // Africa — Southern
  "south africa": "ZAR",
  zimbabwe: "USD",
  zambia: "ZMW",
  malawi: "MWK",
  mozambique: "MZN",
  angola: "AOA",
  namibia: "NAD",
  botswana: "BWP",
  lesotho: "ZAR",
  eswatini: "ZAR",
  swaziland: "ZAR",
  madagascar: "MGA",
  mauritius: "MUR",
  seychelles: "SCR",
  comoros: "USD",
};

// ── Major city name → currency code ─────────────────────────────────────
const CITY: Record<string, string> = {
  // North America
  "new york": "USD",
  nyc: "USD",
  manhattan: "USD",
  brooklyn: "USD",
  queens: "USD",
  "los angeles": "USD",
  la: "USD",
  "san francisco": "USD",
  sf: "USD",
  "silicon valley": "USD",
  chicago: "USD",
  houston: "USD",
  phoenix: "USD",
  philadelphia: "USD",
  "san antonio": "USD",
  "san diego": "USD",
  dallas: "USD",
  "san jose": "USD",
  austin: "USD",
  jacksonville: "USD",
  "fort worth": "USD",
  columbus: "USD",
  charlotte: "USD",
  indianapolis: "USD",
  seattle: "USD",
  denver: "USD",
  boston: "USD",
  nashville: "USD",
  miami: "USD",
  atlanta: "USD",
  portland: "USD",
  minneapolis: "USD",
  washington: "USD",
  dc: "USD",
  "las vegas": "USD",
  memphis: "USD",
  louisville: "USD",
  baltimore: "USD",
  milwaukee: "USD",
  albuquerque: "USD",
  tucson: "USD",
  fresno: "USD",
  sacramento: "USD",
  "kansas city": "USD",
  mesa: "USD",
  omaha: "USD",
  raleigh: "USD",
  cleveland: "USD",
  "virginia beach": "USD",
  "colorado springs": "USD",
  toronto: "CAD",
  vancouver: "CAD",
  montreal: "CAD",
  calgary: "CAD",
  ottawa: "CAD",
  edmonton: "CAD",
  winnipeg: "CAD",
  quebec: "CAD",
  "mexico city": "MXN",
  guadalajara: "MXN",
  monterrey: "MXN",
  cancun: "MXN",
  puebla: "MXN",
  tijuana: "MXN",

  // UK & Ireland
  london: "GBP",
  manchester: "GBP",
  birmingham: "GBP",
  leeds: "GBP",
  glasgow: "GBP",
  edinburgh: "GBP",
  liverpool: "GBP",
  bristol: "GBP",
  sheffield: "GBP",
  cardiff: "GBP",
  nottingham: "GBP",
  leicester: "GBP",
  coventry: "GBP",
  belfast: "GBP",
  newcastle: "GBP",
  brighton: "GBP",
  oxford: "GBP",
  cambridge: "GBP",
  reading: "GBP",
  dublin: "EUR",
  cork: "EUR",
  galway: "EUR",

  // Eurozone
  paris: "EUR",
  marseille: "EUR",
  lyon: "EUR",
  toulouse: "EUR",
  nice: "EUR",
  berlin: "EUR",
  munich: "EUR",
  hamburg: "EUR",
  frankfurt: "EUR",
  cologne: "EUR",
  dusseldorf: "EUR",
  stuttgart: "EUR",
  dortmund: "EUR",
  essen: "EUR",
  madrid: "EUR",
  barcelona: "EUR",
  valencia: "EUR",
  seville: "EUR",
  bilbao: "EUR",
  rome: "EUR",
  milan: "EUR",
  naples: "EUR",
  turin: "EUR",
  florence: "EUR",
  amsterdam: "EUR",
  rotterdam: "EUR",
  "the hague": "EUR",
  brussels: "EUR",
  antwerp: "EUR",
  lisbon: "EUR",
  porto: "EUR",
  vienna: "EUR",
  graz: "EUR",
  athens: "EUR",
  thessaloniki: "EUR",
  helsinki: "EUR",
  tampere: "EUR",
  "luxembourg city": "EUR",

  // Non-euro Europe
  zurich: "CHF",
  geneva: "CHF",
  bern: "CHF",
  basel: "CHF",
  stockholm: "SEK",
  gothenburg: "SEK",
  malmo: "SEK",
  oslo: "NOK",
  bergen: "NOK",
  trondheim: "NOK",
  copenhagen: "DKK",
  aarhus: "DKK",
  reykjavik: "ISK",
  warsaw: "PLN",
  krakow: "PLN",
  gdansk: "PLN",
  wroclaw: "PLN",
  prague: "CZK",
  brno: "CZK",
  budapest: "HUF",
  debrecen: "HUF",
  bucharest: "RON",
  cluj: "RON",
  sofia: "BGN",
  plovdiv: "BGN",
  zagreb: "HRK",
  split: "HRK",
  belgrade: "RSD",
  "novi sad": "RSD",
  sarajevo: "BAM",
  skopje: "MKD",
  tirana: "ALL",
  kyiv: "UAH",
  kharkiv: "UAH",
  odesa: "UAH",
  lviv: "UAH",
  moscow: "RUB",
  "st petersburg": "RUB",
  novosibirsk: "RUB",
  yekaterinburg: "RUB",
  minsk: "BYN",
  chisinau: "MDL",
  tbilisi: "GEL",
  yerevan: "AMD",
  baku: "AZN",
  istanbul: "TRY",
  ankara: "TRY",
  izmir: "TRY",
  antalya: "TRY",

  // Middle East
  dubai: "AED",
  "abu dhabi": "AED",
  sharjah: "AED",
  riyadh: "SAR",
  jeddah: "SAR",
  mecca: "SAR",
  medina: "SAR",
  doha: "QAR",
  "kuwait city": "KWD",
  manama: "BHD",
  muscat: "OMR",
  amman: "JOD",
  petra: "JOD",
  "tel aviv": "ILS",
  jerusalem: "ILS",
  haifa: "ILS",
  beirut: "LBP",
  baghdad: "IQD",
  erbil: "IQD",
  tehran: "IRR",
  mashhad: "IRR",
  isfahan: "IRR",
  "sana'a": "YER",
  aden: "YER",
  damascus: "SYP",
  aleppo: "SYP",

  // South Asia
  mumbai: "INR",
  delhi: "INR",
  bangalore: "INR",
  bengaluru: "INR",
  hyderabad: "INR",
  chennai: "INR",
  kolkata: "INR",
  pune: "INR",
  ahmedabad: "INR",
  surat: "INR",
  jaipur: "INR",
  lucknow: "INR",
  kanpur: "INR",
  nagpur: "INR",
  visakhapatnam: "INR",
  bhopal: "INR",
  karachi: "PKR",
  lahore: "PKR",
  islamabad: "PKR",
  rawalpindi: "PKR",
  faisalabad: "PKR",
  peshawar: "PKR",
  dhaka: "BDT",
  chittagong: "BDT",
  colombo: "LKR",
  kandy: "LKR",
  kathmandu: "NPR",
  kabul: "AFN",

  // East Asia
  beijing: "CNY",
  shanghai: "CNY",
  guangzhou: "CNY",
  shenzhen: "CNY",
  chengdu: "CNY",
  wuhan: "CNY",
  xian: "CNY",
  chongqing: "CNY",
  hangzhou: "CNY",
  nanjing: "CNY",
  tianjin: "CNY",
  dongguan: "CNY",
  tokyo: "JPY",
  osaka: "JPY",
  kyoto: "JPY",
  yokohama: "JPY",
  nagoya: "JPY",
  sapporo: "JPY",
  fukuoka: "JPY",
  seoul: "KRW",
  busan: "KRW",
  incheon: "KRW",
  daegu: "KRW",
  taipei: "TWD",
  kaohsiung: "TWD",
  taichung: "TWD",
  "hong kong": "HKD",
  kowloon: "HKD",
  macau: "MOP",
  macao: "MOP",
  ulaanbaatar: "MNT",

  // Southeast Asia
  bangkok: "THB",
  "chiang mai": "THB",
  phuket: "THB",
  "ho chi minh city": "VND",
  saigon: "VND",
  hanoi: "VND",
  "da nang": "VND",
  "phnom penh": "KHR",
  "siem reap": "KHR",
  vientiane: "LAK",
  "kuala lumpur": "MYR",
  kl: "MYR",
  penang: "MYR",
  "johor bahru": "MYR",
  singapore: "SGD",
  jakarta: "IDR",
  surabaya: "IDR",
  bandung: "IDR",
  medan: "IDR",
  bali: "IDR",
  manila: "PHP",
  "quezon city": "PHP",
  davao: "PHP",
  cebu: "PHP",
  yangon: "MMK",
  mandalay: "MMK",
  naypyidaw: "MMK",
  "bandar seri begawan": "BND",
  dili: "USD",

  // Central Asia
  almaty: "KZT",
  "nur sultan": "KZT",
  astana: "KZT",
  tashkent: "UZS",
  samarkand: "UZS",
  bishkek: "KGS",
  dushanbe: "TJS",
  ashgabat: "TMT",

  // Africa — North
  cairo: "EGP",
  alexandria: "EGP",
  giza: "EGP",
  casablanca: "MAD",
  rabat: "MAD",
  marrakech: "MAD",
  fes: "MAD",
  tangier: "MAD",
  tunis: "TND",
  sfax: "TND",
  algiers: "DZD",
  oran: "DZD",
  constantine: "DZD",
  tripoli: "LYD",
  benghazi: "LYD",
  khartoum: "SDG",

  // Africa — West
  lagos: "NGN",
  abuja: "NGN",
  ibadan: "NGN",
  kano: "NGN",
  "port harcourt": "NGN",
  "benin city": "NGN",
  kaduna: "NGN",
  accra: "GHS",
  kumasi: "GHS",
  tamale: "GHS",
  dakar: "XOF",
  abidjan: "XOF",
  yamoussoukro: "XOF",
  bamako: "XOF",
  ouagadougou: "XOF",
  niamey: "XOF",
  cotonou: "XOF",
  "porto novo": "XOF",
  lome: "XOF",
  conakry: "USD",
  freetown: "USD",
  monrovia: "USD",
  banjul: "USD",
  praia: "USD",

  // Africa — Central
  yaounde: "XAF",
  douala: "XAF",
  bangui: "XAF",
  ndjamena: "XAF",
  libreville: "XAF",
  brazzaville: "XAF",
  "pointe noire": "XAF",
  malabo: "XAF",
  kinshasa: "CDF",
  lubumbashi: "CDF",

  // Africa — East
  nairobi: "KES",
  mombasa: "KES",
  kisumu: "KES",
  "dar es salaam": "TZS",
  dodoma: "TZS",
  zanzibar: "TZS",
  kampala: "UGX",
  entebbe: "UGX",
  "addis ababa": "ETB",
  "dire dawa": "ETB",
  kigali: "RWF",
  bujumbura: "USD",
  mogadishu: "SOS",
  "djibouti city": "USD",
  asmara: "USD",
  juba: "USD",

  // Africa — Southern
  johannesburg: "ZAR",
  joburg: "ZAR",
  "cape town": "ZAR",
  durban: "ZAR",
  pretoria: "ZAR",
  "port elizabeth": "ZAR",
  harare: "USD",
  bulawayo: "USD",
  lusaka: "ZMW",
  ndola: "ZMW",
  lilongwe: "MWK",
  blantyre: "MWK",
  maputo: "MZN",
  luanda: "AOA",
  windhoek: "NAD",
  gaborone: "BWP",
  antananarivo: "MGA",
  "port louis": "MUR",
  victoria: "SCR",

  // Latin America
  "sao paulo": "BRL",
  "rio de janeiro": "BRL",
  rio: "BRL",
  brasilia: "BRL",
  salvador: "BRL",
  fortaleza: "BRL",
  "belo horizonte": "BRL",
  manaus: "BRL",
  "buenos aires": "ARS",
  cordoba: "ARS",
  rosario: "ARS",
  bogota: "COP",
  medellin: "COP",
  cali: "COP",
  cartagena: "COP",
  santiago: "CLP",
  valparaiso: "CLP",
  lima: "PEN",
  arequipa: "PEN",
  caracas: "USD",
  guayaquil: "USD",
  quito: "USD",
  "la paz": "BOB",
  "santa cruz": "BOB",
  asuncion: "PYG",
  montevideo: "UYU",
  georgetown: "USD",
  paramaribo: "USD",
  "guatemala city": "GTQ",
  tegucigalpa: "HNL",
  "san salvador": "USD",
  managua: "NIO",
  "panama city": "USD",
  havana: "USD",
  "port au prince": "USD",
  "santo domingo": "DOP",
  kingston: "JMD",
  "port of spain": "TTD",

  // Oceania
  sydney: "AUD",
  melbourne: "AUD",
  brisbane: "AUD",
  perth: "AUD",
  adelaide: "AUD",
  canberra: "AUD",
  "gold coast": "AUD",
  darwin: "AUD",
  auckland: "NZD",
  wellington: "NZD",
  christchurch: "NZD",
  "port moresby": "PGK",
  suva: "FJD",
};

// ── Normalise input ───────────────────────────────────────────────────────
const STOP =
  /\b(city|state|province|county|district|region|area|capital|federal|republic|democratic|peoples|people|island|islands|territory|territories|north|south|east|west|central|new|greater|metro)\b/g;

function normalise(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/[,.\-()[\]/]/g, " ")
    .replace(STOP, " ")
    .replace(/\s+/g, " ")
    .trim();
}

// ── Detection ─────────────────────────────────────────────────────────────
export function getCurrencyForLocation(raw: string): CurrencyInfo {
  if (!raw.trim()) return CURRENCIES.USD;

  const input = normalise(raw);
  if (!input) return CURRENCIES.USD;

  // Helpers
  const buildCurrencyInfo = (code: string): CurrencyInfo => {
    if (CURRENCIES[code]) return CURRENCIES[code];
    const symbol = getSymbolFromCurrency(code) || code;
    return { symbol, code, minRent: 1000, maxRent: 50000 };
  };

  // 1. Try resolving using i18n-iso-countries
  // raw could be "Nigeria", "Austin, TX", "usa", "uk"
  const isoCode = countries.getAlpha2Code(raw, 'en') || countries.getAlpha2Code(input, 'en');
  if (isoCode) {
    const code = countryToCurrency[isoCode as keyof typeof countryToCurrency];
    if (code) return buildCurrencyInfo(code);
  }

  // 2. Exact match — city first, then country, then alias
  if (CITY[input]) return buildCurrencyInfo(CITY[input]);
  if (COUNTRY[input]) return buildCurrencyInfo(COUNTRY[input]);

  // 3. Try each whitespace-separated word (handles "Lagos, Nigeria" → "lagos nigeria")
  const words = input.split(" ");
  for (const w of words) {
    if (w.length < 3) continue;
    
    // Also check i18n-iso-countries for each word (e.g. "Lagos, Nigeria" -> checks "Nigeria")
    const wordIso = countries.getAlpha2Code(w, 'en');
    if (wordIso) {
      const code = countryToCurrency[wordIso as keyof typeof countryToCurrency];
      if (code) return buildCurrencyInfo(code);
    }
    
    if (CITY[w]) return buildCurrencyInfo(CITY[w]);
    if (COUNTRY[w]) return buildCurrencyInfo(COUNTRY[w]);
  }

  // 4. Substring: input contains a key
  for (const [k, v] of Object.entries(CITY)) {
    if (input.includes(k)) return buildCurrencyInfo(v);
  }
  for (const [k, v] of Object.entries(COUNTRY)) {
    if (input.includes(k)) return buildCurrencyInfo(v);
  }

  // 5. Substring: key contains input (handles partial typing like "nige" → NGN)
  if (input.length >= 4) {
    for (const [k, v] of Object.entries(CITY)) {
      if (k.includes(input)) return buildCurrencyInfo(v);
    }
    for (const [k, v] of Object.entries(COUNTRY)) {
      if (k.includes(input)) return buildCurrencyInfo(v);
    }
  }

  return CURRENCIES.USD;
}

export { CURRENCIES };
export const DEFAULT_CURRENCY: CurrencyInfo = CURRENCIES.USD;
